// English translations of the Spanish interface texts (t("…") keys).
// `npm run check:i18n` fails when a key is missing.

export const en: Record<string, string> = {
  "Éxito al primer intento": "First-attempt success",
  "Dependencia de pistas": "Hint dependency",
  "Intentos hasta el dominio": "Retries to mastery",
  "Retención a 7 días": "Retention 7d",
  "Retención a 30 días": "Retention 30d",
  "Tasa de causa raíz en incidentes": "Incident root-cause rate",
  "Tasa de aprobado en proyectos finales": "Capstone pass rate",
  "Cobertura de habilidades": "Skill coverage",
  "Aprovisionamiento p95": "Provisioning p95",
  "Tasa de error del evaluador": "Grader error rate",
  "Laboratorios con corrección automática": "Auto-graded labs",
  "Tasa de fallos de infraestructura": "Infra failure rate",
  "Consola del instructor": "Instructor console",
  "Clase": "Class",
  "Todo el alumnado": "All learners",
  "Nombre de la nueva clase": "New class name",
  "Crear clase": "Create class",
  "KPI de aprendizaje": "Learning KPIs",
  "{n} alumnos activos · {a} intentos": "{n} active learners · {a} attempts",
  "Valor": "Value",
  "Objetivo": "Target",
  "Analítica de la clase": "Class analytics",
  "correo del alumno": "learner email",
  "Añadir alumno": "Add learner",
  "Dominio del equipo por rama": "Team branch mastery",
  "Alumnado": "Learners",
  "Nombre": "Name",
  "Nivel": "Level",
  "Mejor preparación": "Best readiness",
  "Selecciona una clase para ver su alumnado y el mapa de calor de habilidades del equipo.": "Select a class to see its learners and team skill heatmap.",
  "Calibración de dificultad por laboratorio": "Per-lab difficulty calibration",
  "Pool de proyectos reales de GCP (F2)": "Real-GCP project pool (F2)",
  "Controlador:": "Driver:",
  "Ejecutar la limpieza ahora": "Run janitor now",
  "No hay pool de sandboxes configurado; los laboratorios se ejecutan en el simulador y los emuladores.": "No sandbox pool configured; labs run on the simulator and emulators.",
  "Salud del contenido": "Content health",
  "{n} laboratorios cargados · {p} problemas": "{n} labs loaded · {p} problems",
  "Todo el contenido es válido.": "All content validates.",
  "Tipos de fallo: {list}": "Fault types: {list}",
  "Catálogo de laboratorios": "Lab catalog",
  "Ruta": "Track",
  "Todas las rutas": "All tracks",
  "Buscar laboratorios o habilidades…": "Search labs or skills…",
  "Buscar": "Search",
  "{n} laboratorios": "{n} labs",
  "día {n}": "day {n}",
  "dificultad {n} de 5": "difficulty {n} of 5",
  "¿Empezar de nuevo? Se perderá la historia de tu empresa.": "Start over? Your company's history will be lost.",
  "Cargando…": "Loading…",
  "Únete a {name}": "Join {name}",
  "Eres la nueva persona de ingeniería cloud en {name}. Su entorno de Google Cloud persiste entre misiones: lo que construyes se queda, lo que dejas inseguro o sin copia de seguridad vuelve como incidentes, y la disponibilidad, la postura de seguridad, el coste y la satisfacción de las partes interesadas son responsabilidad tuya.": "You are the new cloud engineer at {name}. Its Google Cloud estate persists between missions: what you build stays, what you leave insecure or unbacked-up comes back as incidents, and the company's availability, security posture, cost and stakeholder satisfaction are yours to look after.",
  "Proyectos": "Projects",
  "Empezar el día 1": "Start day 1",
  "{name} — día {day}": "{name} — day {day}",
  "Empezar de nuevo": "Start over",
  "Disponibilidad": "Availability",
  "Postura de seguridad": "Security posture",
  "Coste mensual": "Monthly cost",
  "Satisfacción de las partes interesadas": "Stakeholder satisfaction",
  "Consecuencias abiertas": "Open consequences",
  "Responder": "Respond",
  "Misiones": "Missions",
  "incidente": "incident",
  "hecha": "done",
  "Reanudar": "Resume",
  "Empezar": "Start",
  "bloqueada": "locked",
  "Diario": "Journal",
  "Día {n}": "Day {n}",
  "Nada todavía.": "Nothing yet.",
  "Personas": "People",
  "No hay nada en cola: elige cualquier laboratorio del catálogo.": "Nothing queued: pick any lab from the catalog.",
  "Hola de nuevo, {name}": "Welcome back, {name}",
  "Descargar expediente firmado": "Download signed transcript",
  "{xp} XP · {bonus} de bonificación · racha de {streak} días": "{xp} XP · {bonus} bonus · {streak}-day streak",
  "Etapa profesional": "Career stage",
  "Siguiente:": "Next:",
  "Autonomía": "Autonomy",
  "Laboratorios en curso": "Labs in progress",
  "empezado el {date}": "started {date}",
  "Plan adaptativo": "Adaptive plan",
  "Recomendaciones de la ruta": "Track recommendations",
  "Dimensiones de competencia": "Competence dimensions",
  "{pct}% · {n} evid.": "{pct}% · {n} evid.",
  "Céntrate ahora en: {list}": "Focus now on: {list}",
  "Preparación para certificaciones": "Certification readiness",
  "Retención": "Retention",
  "Habilidad": "Skill",
  "Recuerdo": "Recall",
  "Repaso": "Review",
  "toca repasar": "review due",
  "Supera laboratorios sin pistas para empezar a construir memoria duradera.": "Pass labs without hints to start building durable memory.",
  "Errores recurrentes": "Recurring errors",
  "Habilidades": "Skills",
  "Dominio": "Mastery",
  "dominada": "mastered",
  "Todavía no hay habilidades medidas.": "No skills measured yet.",
  "Especializaciones": "Specializations",
  "completada": "completed",
  "Falta: {list}": "Missing: {list}",
  "Insignias": "Badges",
  "Aún ninguna.": "None yet.",
  "Generador de incidentes": "Incident generator",
  "Los incidentes se componen a partir de una biblioteca de fallos: un sistema, uno o varios modos de fallo, un contexto de negocio y una dificultad. Con más dificultad los tickets son vagos o engañosos, se acumulan varios fallos y el modo producción activa una sala de crisis P1. Nunca verás qué fallo se ha inyectado.": "Incidents are composed from a failure library: a system, one or more failure modes, a business context and a difficulty. At higher difficulty tickets get vague or misleading, several failures stack, and production mode runs a P1 war room. You never see which failure was injected.",
  "Sistema": "System",
  "Síntoma": "Symptom",
  "Cualquiera (sorpréndeme)": "Any (surprise me)",
  "Contexto de negocio": "Business context",
  "Aleatorio": "Random",
  "Dificultad: {n}": "Difficulty: {n}",
  "Modo": "Mode",
  "Ticket estándar": "Standard ticket",
  "Producción (sala de crisis P1)": "Production (P1 war room)",
  "Problema desconocido (solo se conoce el impacto)": "Unknown problem (only the impact is known)",
  "Preparando el entorno…": "Building the environment…",
  "Generar incidente": "Generate incident",
  "Grafo de síntomas": "Symptom graph",
  "Dónde buscar para cada síntoma, capa por capa.": "Where to look for each symptom, layer by layer.",
  "Objetivos": "Objectives",
  "Restricciones": "Constraints",
  "Cómo se te evaluará": "How you will be graded",
  "crítico": "critical",
  "{n} ptos.": "{n} pts",
  "Fidelidad": "Fidelity",
  "F0 — simulador": "F0 — simulator",
  "F1 — emuladores": "F1 — emulators",
  "F2 — proyecto real de GCP": "F2 — real GCP project",
  "Empezar laboratorio": "Start lab",
  "Este laboratorio no tiene ticket. Usa la terminal y los objetivos de la izquierda.": "This lab has no ticket. Use the terminal and the objectives on the left.",
  "Impacto:": "Impact:",
  "Abierto por {who}": "Opened by {who}",
  "servicio {name}": "{name} service",
  "público": "public",
  "Trabaja el ticket desde la terminal:": "Work the ticket from the terminal:",
  "nombre": "name",
  "pregunta": "question",
  "Conversaciones": "Conversations",
  "Tú → {who}:": "You → {who}:",
  "Consulta de registros": "Log query",
  "Ejecutar consulta": "Run query",
  "Hora": "Time",
  "Gravedad": "Severity",
  "Recurso": "Resource",
  "por": "by",
  "Ninguna entrada coincide.": "No entries match.",
  "Guardado {file}": "Saved {file}",
  "archivo nuevo (p. ej. main.tf)": "new file (e.g. main.tf)",
  "Nombre del archivo nuevo": "New file name",
  "Guardar": "Save",
  "Elige un archivo o crea uno. Los archivos se comparten con la terminal": "Pick a file or create one. Files are shared with the terminal",
  "Aún no hay nada aquí.": "Nothing here yet.",
  "Todavía no hay recursos.": "No resources yet.",
  "Aún no hay métricas. Aparecen a medida que avanza el tiempo simulado.": "No metrics yet. They appear as simulated time passes.",
  "€/mes": "€/month",
  "Comandos que has ejecutado, con su salida": "Commands you ran, with their output",
  "Comando": "Command",
  "salida": "output",
  "Superado": "Passed",
  "Aún no superado": "Not passed yet",
  "Ha fallado un criterio crítico.": "A critical criterion failed.",
  "de bonificación": "bonus",
  "Cómo has trabajado": "How you worked",
  "Cambios antes de reunir evidencias:": "Changes before gathering evidence:",
  "Restricciones incumplidas:": "Constraints violated:",
  "Mentor": "Mentor",
  "Revisión del post-mortem": "Post-mortem review",
  "Día {n}.": "Day {n}.",
  "Quedan {n} riesgo(s) latente(s) en el entorno…": "{n} latent risk(s) remain in the estate…",
  "Ningún riesgo latente nuevo.": "No new latent risks.",
  "Volver a la empresa →": "Back to the company →",
  "Panel": "Dashboard",
  "Más laboratorios": "More labs",
  "¿Enviar para evaluar? El entorno se cerrará.": "Submit for grading? The environment will be closed.",
  "¿Abandonar este laboratorio?": "Abandon this lab?",
  "Cronología": "Timeline",
  "Instrucciones": "Instructions",
  "Ayuda": "Help",
  "recurso": "resource",
  "Pista (quedan {n})": "Hint ({n} left)",
  "Comprobar": "Check",
  "Evidencias": "Evidence",
  "Preguntas": "Questions",
  "Justifica tu elección": "Justify your choice",
  "Enviar": "Submit",
  "Abandonar": "Abandon",
  "La sesión caduca a las {time}.": "The session expires at {time}.",
  "Modo lector de pantalla para la terminal": "Screen-reader mode for the terminal",
  "Esta sesión está en estado «{status}».": "This session is {status}.",
  "Empezar un intento nuevo →": "Start a new attempt →",
  "Liga semanal": "Weekly league",
  "Las ligas son voluntarias y ordenan la XP de esta semana ponderada por dificultad: los laboratorios difíciles cuentan más que repetir los fáciles.": "Leagues are opt-in and rank this week's XP weighted by difficulty, so hard labs count more than grinding easy ones.",
  "Liga {name}": "League {name}",
  "Salir de la clasificación": "Leave leaderboard",
  "Unirme a la clasificación": "Join leaderboard",
  "Puntos": "Points",
  "Nadie ha puntuado en esta liga esta semana.": "No one has scored in this league this week.",
  "Aprende Google Cloud haciendo el trabajo: construye, rompe, diagnostica y repara sistemas en un simulador determinista, gestiona una empresa persistente, atiende tickets de personas que no conocen la causa raíz y da el salto a entornos reales.": "Learn Google Cloud by doing the job: build, break, diagnose and fix systems in a deterministic simulator, run a persistent company, work tickets from people who don't know the root cause, and graduate to real environments.",
  "Flujos reales con gcloud, gsutil, bq, kubectl y terraform": "Real gcloud, gsutil, bq, kubectl and terraform workflows",
  "Incidentes generados a partir de una biblioteca de fallos, salas de crisis P1 y experimentos de caos": "Incidents generated from a failure library, P1 war rooms and chaos experiments",
  "Evaluación del proceso: diagnóstico, seguridad, coste, riesgo y comunicación": "Process grading: diagnosis, security, cost, risk and communication",
  "Nueve dimensiones de competencia, retención espaciada y una escalera de autonomía": "Nine competence dimensions, spaced retention and an autonomy ladder",
  "Etapas de carrera de becario a arquitecto con expedientes verificables": "Career stages from intern to architect with verifiable transcripts",
  "Iniciar sesión": "Sign in",
  "Crear cuenta": "Create account",
  "Correo electrónico": "Email",
  "Nombre visible": "Display name",
  "Contraseña": "Password",
  "Entrar con Google Workspace (si está configurado)": "Sign in with Google Workspace (if configured)",
  "Verificar el expediente de un alumno": "Verify a learner's transcript",
  "Grafo de habilidades": "Skill graph",
  "Las habilidades se desbloquean en orden de dependencias. Verde es dominada (≥80), ámbar está en progreso.": "Skills unlock in dependency order. Green is mastered (≥80), amber is in progress.",
  "Rama": "Branch",
  "Todas las ramas ({n} habilidades)": "All branches ({n} skills)",
  "Dominio por rama": "Branch mastery",
  "Trayectoria profesional": "Career path",
  "Etapa {n}": "Stage {n}",
  "Proyectos finales:": "Capstones:",
  "Verificar un expediente": "Verify a transcript",
  "El alumnado puede descargar un expediente firmado con sus competencias, su etapa profesional y los proyectos finales completados. Pégalo aquí para comprobar que lo emitió esta plataforma y que no se ha modificado.": "Learners can download a signed transcript of their competences, career stage and completed capstones. Paste it here to check that it was issued by this platform and has not been modified.",
  "{ … JSON del expediente … }": "{ … transcript JSON … }",
  "Verificar": "Verify",
  "Volver": "Back",
  "✓ Expediente válido": "✓ Valid transcript",
  "✗ Firma no válida": "✗ Invalid signature",
  "etapa profesional": "career stage",
  "emitido el {date}": "issued {date}",
  "Autonomía: {a} · {n} laboratorios superados · especializaciones: {s}": "Autonomy: {a} · {n} labs passed · specializations: {s}",
  "ninguna": "none",
  "Laboratorios": "Labs",
  "Incidentes": "Incidents",
  "Empresa": "Company",
  "Ligas": "Leagues",
  "Idioma": "Language",
  "Principal": "Main",
  "Saltar al contenido": "Skip to content",
  "Instructor": "Instructor",
  "Cerrar sesión": "Sign out",
  "…": "…",
  "siguiente": "next",
  "refuerzo": "remediation",
  "repetición": "retest",
  "simulacro": "mock exam",
  "repaso": "review",
  "incidente sorpresa": "surprise incident",
  "dimensión": "dimension",
  "nuevo": "new",
  "Conocimiento": "Knowledge",
  "Ejecución": "Execution",
  "Resolución de problemas": "Troubleshooting",
  "Arquitectura": "Architecture",
  "Seguridad": "Security",
  "Coste": "Cost",
  "Operaciones": "Operations",
  "básico": "basic",
  "intermedio": "intermediate",
  "avanzado": "advanced",
  "profesional": "professional",
  "guiado": "guided",
  "reto": "challenge",
  "test": "quiz",
  "proyecto final": "capstone",
  "jefe final": "boss",
  "caso práctico": "case study",
  "entrevista": "interview",
  "producción": "production",
  "problema desconocido": "unknown problem",
  "carrera": "career",
  "arquitectura": "architecture",
  "aprendizaje": "learn",
  "laboratorio": "lab",
  "ticket": "ticket",
  "consola": "console",
  "topología": "topology",
  "registros": "logs",
  "métricas": "metrics",
  "IAM": "IAM",
  "coste": "cost",
  "archivos": "files",
  "historial": "history",
  "resolución": "resolution",
  "diagnóstico": "diagnosis",
  "seguridad": "security",
  "eficiencia": "efficiency",
  "riesgo": "risk",
  "comunicación": "communication",
  "documentación": "documentation",
  "autonomía": "autonomy",
  "NUEVO": "NEW",
  "EN CURSO": "IN PROGRESS",
  "RESUELTO": "RESOLVED",
  "ESCALADO": "ESCALATED",
  "desarrollo": "developer",
  "finanzas": "finance",
  "dirección": "manager",
  "cliente": "customer",
  "SRE": "SRE",
  "operaciones": "ops",
  "Causa raíz": "Root cause",
  "Corrección": "Fix",
  "Verificación": "Verification",
  "Prevención": "Prevention",
  "Post-mortem": "Post-mortem",
  "Explicación": "Explanation",
  "Decisiones de diseño": "Design decisions",
  "Plan de despliegue": "Rollout plan",
  "funcional": "functional",
  "estado": "state",
  "fiabilidad": "reliability",
  "evidencia": "evidence",
  "preguntas": "quiz",
  "pista": "hint",
  "pista parcial": "partial hint",
  "solución": "solution",
  "No modifiques {name} (pertenece a otro equipo)": "Do not modify {name} (it belongs to another team)",
  "Sin interrupción del servicio": "No downtime",
  "Nada público (sin allUsers ni allAuthenticatedUsers)": "Nothing public (no allUsers or allAuthenticatedUsers)",
  "Sin roles básicos (Owner, Editor, Viewer)": "No basic roles (Owner, Editor, Viewer)",
  "No borres recursos": "Do not delete resources",
  "DNS": "DNS",
  "balanceador de carga": "load balancer",
  "salud de los backends": "backend health",
  "cortafuegos": "firewall",
  "tiempos de espera": "timeouts",
  "aplicación": "application",
  "preparación de pods (readiness)": "pod readiness",
  "carga de trabajo de Kubernetes": "Kubernetes workload",
  "Service de Kubernetes": "Kubernetes Service",
  "versión desplegada": "release",
  "configuración": "configuration",
  "identidad y permisos": "identity and permissions",
  "camino de red": "network path",
  "base de datos": "database",
  "cuotas": "quotas",
  "capacidad": "capacity",
  "pool de conexiones": "connection pool",
  "autoescalado": "autoscaling",
  "permisos de almacenamiento": "storage permissions",
  "permisos del servicio": "service permissions",
  "políticas de organización": "organization policies",
  "cómputo": "compute",
  "almacenamiento": "storage",
  "tráfico de salida": "egress traffic",
  "procesamiento de datos": "data processing",
  "recursos ociosos": "idle resources",
  "etiquetas de red": "network tags",
  "comprobación de estado": "health check",
  "Cargando el editor…": "Loading editor…",
  "sin datos": "no data",
  "Terminal de Cloud Shell. Escribe comandos y pulsa Intro.": "Cloud Shell terminal. Type commands and press Enter.",
  // graphical console
  "La terminal no está lista.": "The terminal is not ready.",
  "Consola": "Console",
  "IAM y administración": "IAM & Admin",
  "Gestión": "Management",
  "Cuentas de servicio": "Service accounts",
  "APIs y servicios": "APIs & Services",
  "APIs y servicios habilitados": "Enabled APIs & services",
  "Compute Engine": "Compute Engine",
  "Computación": "Compute",
  "Instancias de VM": "VM instances",
  "Discos": "Disks",
  "Kubernetes Engine": "Kubernetes Engine",
  "Clústeres": "Clusters",
  "Cloud Run": "Cloud Run",
  "Sin servidor": "Serverless",
  "Servicios": "Services",
  "Cloud Storage": "Cloud Storage",
  "Almacenamiento": "Storage",
  "Buckets": "Buckets",
  "SQL": "SQL",
  "Bases de datos": "Databases",
  "Instancias": "Instances",
  "BigQuery": "BigQuery",
  "Analíticas": "Analytics",
  "Estudio de BigQuery": "BigQuery Studio",
  "Pub/Sub": "Pub/Sub",
  "Temas y suscripciones": "Topics and subscriptions",
  "Red de VPC": "VPC network",
  "Redes": "Networking",
  "Redes de VPC": "VPC networks",
  "Cortafuegos": "Firewall",
  "Secret Manager": "Secret Manager",
  "Secretos": "Secrets",
  "Logging": "Logging",
  "Monitoring": "Monitoring",
  "Facturación": "Billing",
  "Menú de navegación": "Navigation menu",
  "Seleccionar un proyecto": "Select a project",
  "Este laboratorio trabaja en un único proyecto. En la terminal: gcloud config get-value project": "This lab works in a single project. In the terminal: gcloud config get-value project",
  "Buscar recursos, documentos, productos y más": "Search for resources, docs, products and more",
  "Buscar productos": "Search products",
  "Activar Cloud Shell": "Activate Cloud Shell",
  "Notificaciones": "Notifications",
  "correcto": "succeeded",
  "con error": "failed",
  "No hay operaciones recientes.": "No recent operations.",
  "Cómo funciona esta consola": "How this console works",
  "Cada botón ejecuta el comando equivalente en Cloud Shell (abajo): míralo para aprender la línea de comandos.": "Every button runs the equivalent command in Cloud Shell (below): watch it to learn the command line.",
  "Los formularios muestran el «Código equivalente» mientras los rellenas; puedes pegarlo en la terminal para editarlo.": "Forms show the \"Equivalent code\" as you fill them in; you can paste it into the terminal to edit it.",
  "Lo que hagas en la terminal aparece aquí al instante, y la evaluación tiene en cuenta ambos.": "What you do in the terminal shows up here immediately, and grading takes both into account.",
  "Contenido de la consola": "Console content",
  "Descripción general de Cloud": "Cloud overview",
  "Ver en Cloud Shell": "View in Cloud Shell",
  "Cerrar": "Close",
  "Minúsculas, números y guiones; empieza por una letra.": "Lowercase letters, numbers and hyphens; starts with a letter.",
  "Actualizar": "Refresh",
  "y {n} más": "and {n} more",
  "Buckets de Cloud Storage": "Cloud Storage buckets",
  "Servicios de Cloud Run": "Cloud Run services",
  "Instancias de Cloud SQL": "Cloud SQL instances",
  "Clústeres de GKE": "GKE clusters",
  "Temas de Pub/Sub": "Pub/Sub topics",
  "Conjuntos de datos de BigQuery": "BigQuery datasets",
  "Reglas de cortafuegos": "Firewall rules",
  "Información del proyecto": "Project info",
  "Nombre del proyecto": "Project name",
  "ID del proyecto": "Project ID",
  "Número del proyecto": "Project number",
  "Región predeterminada": "Default region",
  "Coste mensual estimado de los recursos actuales.": "Estimated monthly cost of the current resources.",
  "Ver el detalle de costes →": "View cost details →",
  "APIs": "APIs",
  "APIs habilitadas en el proyecto.": "APIs enabled in the project.",
  "Ir a APIs y servicios →": "Go to APIs & Services →",
  "Recursos": "Resources",
  "Actividad": "Activity",
  "Todavía no has hecho cambios. Lo que hagas aquí o en Cloud Shell aparecerá en esta lista.": "You haven't made changes yet. What you do here or in Cloud Shell will appear in this list.",
  "Usuario": "User",
  "Cuenta de servicio": "Service account",
  "Grupo": "Group",
  "Cualquiera en internet": "Anyone on the internet",
  "Cualquier cuenta de Google": "Any Google account",
  "Permisos del proyecto {p}: quién (principal) tiene qué rol.": "Permissions for project {p}: who (principal) has which role.",
  "Conceder acceso": "Grant access",
  "Principales y roles del proyecto": "Project principals and roles",
  "La política del proyecto no tiene vinculaciones.": "The project policy has no bindings.",
  "Tipo": "Type",
  "Roles": "Roles",
  "condicional": "conditional",
  "Quitar {role} a {who}": "Remove {role} from {who}",
  "Conceder acceso a {p}": "Grant access to {p}",
  "Tipo de principal": "Principal type",
  "Rol": "Role",
  "Otro rol…": "Another role…",
  "Rol personalizado o predefinido": "Custom or predefined role",
  "¿Quitar el rol?": "Remove role?",
  "{who} dejará de tener {role} en el proyecto.": "{who} will no longer have {role} on the project.",
  "Quitar": "Remove",
  "Quitar un rol": "Remove a role",
  "Identidades que usan las aplicaciones y las VM para llamar a las APIs de Google Cloud.": "Identities that applications and VMs use to call Google Cloud APIs.",
  "No hay cuentas de servicio.": "There are no service accounts.",
  "Estado": "Status",
  "Correo": "Email",
  "Claves": "Keys",
  "Crear cuenta de servicio": "Create service account",
  "Crear": "Create",
  "ID de la cuenta de servicio": "Service account ID",
  "De 6 a 30 caracteres: minúsculas, números y guiones.": "6 to 30 characters: lowercase letters, numbers and hyphens.",
  "Inhabilitar": "Disable",
  "Inhabilitar cuenta de servicio": "Disable service account",
  "Habilitar": "Enable",
  "Habilitar cuenta de servicio": "Enable service account",
  "Eliminar": "Delete",
  "Eliminar cuenta de servicio": "Delete service account",
  "¿Eliminar las cuentas de servicio?": "Delete service accounts?",
  "Lo que dependa de ellas dejará de poder autenticarse.": "Anything that depends on them will no longer be able to authenticate.",
  "No hay instancias de VM en este proyecto.": "There are no VM instances in this project.",
  "Zona": "Zone",
  "Tipo de máquina": "Machine type",
  "IP interna": "Internal IP",
  "IP externa": "External IP",
  "Ninguna": "None",
  "Etiquetas de red": "Network tags",
  "Conectar": "Connect",
  "Crear instancia": "Create instance",
  "Crear una instancia": "Create an instance",
  "Crear instancia de VM": "Create VM instance",
  "Imagen del disco de arranque": "Boot disk image",
  "Red": "Network",
  "Subred": "Subnetwork",
  "Automática": "Automatic",
  "Separadas por comas. Las reglas de cortafuegos se aplican por etiqueta.": "Comma-separated. Firewall rules apply by tag.",
  "Permitir tráfico HTTP": "Allow HTTP traffic",
  "Añade la etiqueta http-server. Hace falta una regla de cortafuegos que la permita.": "Adds the http-server tag. A firewall rule that allows it is needed.",
  "Permitir tráfico HTTPS": "Allow HTTPS traffic",
  "Añade la etiqueta https-server.": "Adds the https-server tag.",
  "Asignar una IP externa": "Assign an external IP",
  "Sin IP externa la VM solo sale a internet a través de Cloud NAT.": "Without an external IP the VM only reaches the internet through Cloud NAT.",
  "VM Spot (más barata, puede detenerse en cualquier momento)": "Spot VM (cheaper, can be stopped at any time)",
  "Predeterminada de Compute Engine": "Compute Engine default",
  "Iniciar": "Start",
  "Iniciar VM": "Start VM",
  "Detener": "Stop",
  "Detener VM": "Stop VM",
  "Restablecer": "Reset",
  "Restablecer VM": "Reset VM",
  "Eliminar VM": "Delete VM",
  "¿Eliminar las instancias?": "Delete instances?",
  "Se borrarán las VM seleccionadas y sus discos de arranque.": "The selected VMs and their boot disks will be deleted.",
  "Discos persistentes": "Persistent disks",
  "No hay discos.": "There are no disks.",
  "Tamaño": "Size",
  "En uso por": "In use by",
  "Crear disco": "Create disk",
  "Crear un disco": "Create a disk",
  "Tipo de disco": "Disk type",
  "Tamaño (GB)": "Size (GB)",
  "Eliminar disco": "Delete disk",
  "¿Eliminar los discos?": "Delete disks?",
  "Los datos del disco se perderán.": "The disk data will be lost.",
  "No hay redes de VPC.": "There are no VPC networks.",
  "Modo de subred": "Subnet mode",
  "Automático": "Auto",
  "Personalizado": "Custom",
  "Subredes": "Subnets",
  "Emparejamientos": "Peerings",
  "Acceso a servicios privados": "Private services access",
  "Sí": "Yes",
  "No": "No",
  "Crear red de VPC": "Create VPC network",
  "Crear una red de VPC": "Create a VPC network",
  "Modo de creación de subredes": "Subnet creation mode",
  "Eliminar red de VPC": "Delete VPC network",
  "¿Eliminar las redes?": "Delete networks?",
  "Antes hay que borrar sus subredes, reglas y VM.": "Their subnets, rules and VMs must be deleted first.",
  "Mostrar las subredes automáticas de todas las regiones": "Show auto-mode subnets in all regions",
  "No hay subredes.": "There are no subnets.",
  "Región": "Region",
  "Rango de IP": "IP range",
  "Acceso privado a Google": "Private Google Access",
  "Activado": "On",
  "Desactivado": "Off",
  "Registros de flujo": "Flow logs",
  "Añadir subred": "Add subnet",
  "Añadir una subred": "Add a subnet",
  "Añadir": "Add",
  "Rango de IPv4": "IPv4 range",
  "En notación CIDR; no puede solaparse con otras subredes de la red.": "In CIDR notation; it can't overlap other subnets in the network.",
  "Permite a las VM sin IP externa usar las APIs de Google.": "Lets VMs without an external IP use Google APIs.",
  "Eliminar subred": "Delete subnet",
  "¿Eliminar las subredes?": "Delete subnets?",
  "Las VM que las usan tienen que borrarse antes.": "The VMs that use them must be deleted first.",
  "Se evalúan por prioridad: el número más bajo gana. Sin regla que lo permita, el tráfico entrante se bloquea.": "Rules are evaluated by priority: the lowest number wins. Without a rule that allows it, incoming traffic is blocked.",
  "No hay reglas de cortafuegos.": "There are no firewall rules.",
  "Salida": "Egress",
  "Entrada": "Ingress",
  "Destinos": "Targets",
  "Todas las instancias": "All instances",
  "Filtros": "Filters",
  "Protocolos/puertos": "Protocols/ports",
  "Acción": "Action",
  "Denegar": "Deny",
  "Permitir": "Allow",
  "Prioridad": "Priority",
  "Inhabilitada": "Disabled",
  "Habilitada": "Enabled",
  "Crear regla de cortafuegos": "Create firewall rule",
  "Crear una regla de cortafuegos": "Create a firewall rule",
  "Dirección del tráfico": "Direction of traffic",
  "Acción si hay coincidencia": "Action on match",
  "De 0 a 65535; el número más bajo tiene más prioridad.": "0 to 65535; the lowest number has the highest priority.",
  "Etiquetas de destino": "Target tags",
  "Vacío = todas las instancias de la red.": "Empty = all instances in the network.",
  "Rangos de IP": "IP ranges",
  "Origen (entrada) o destino (salida), separados por comas. 0.0.0.0/0 es todo internet.": "Source (ingress) or destination (egress), comma-separated. 0.0.0.0/0 is the whole internet.",
  "Protocolos y puertos": "Protocols and ports",
  "p. ej. tcp:22, udp:53, icmp o all.": "e.g. tcp:22, udp:53, icmp or all.",
  "Registros de cortafuegos": "Firewall logs",
  "Inhabilitar regla": "Disable rule",
  "Habilitar regla": "Enable rule",
  "Eliminar regla de cortafuegos": "Delete firewall rule",
  "¿Eliminar las reglas?": "Delete rules?",
  "El tráfico que permitían quedará bloqueado (o permitido, si eran de denegación).": "The traffic they allowed will be blocked (or allowed, if they were deny rules).",
  "No hay buckets en este proyecto.": "There are no buckets in this project.",
  "Ubicación": "Location",
  "región": "region",
  "birregión": "dual-region",
  "multirregión": "multi-region",
  "Acceso público": "Public access",
  "Público en internet": "Public to internet",
  "Prevenido": "Prevented",
  "No público": "Not public",
  "Control de acceso": "Access control",
  "Uniforme": "Uniform",
  "Detallado": "Fine-grained",
  "Versiones": "Versioning",
  "Objetos": "Objects",
  "Crear bucket": "Create bucket",
  "Crear un bucket": "Create a bucket",
  "Único en todo el mundo: minúsculas, números, guiones y puntos.": "Globally unique: lowercase letters, numbers, hyphens and dots.",
  "EU (multirregión)": "EU (multi-region)",
  "US (multirregión)": "US (multi-region)",
  "Clase de almacenamiento": "Storage class",
  "Acceso uniforme a nivel de bucket": "Uniform bucket-level access",
  "Solo IAM decide quién accede (sin ACL por objeto).": "Only IAM decides who has access (no per-object ACLs).",
  "Aplicar la prevención de acceso público": "Enforce public access prevention",
  "Impide que el bucket se haga público por error.": "Stops the bucket from being made public by mistake.",
  "Activar versiones": "Enable versioning",
  "Activar versiones de objetos": "Enable object versioning",
  "Prevenir acceso público": "Prevent public access",
  "Eliminar bucket": "Delete bucket",
  "¿Eliminar los buckets?": "Delete buckets?",
  "Se borrarán los buckets y todos sus objetos.": "The buckets and all their objects will be deleted.",
  "Subir un archivo…": "Upload a file…",
  "Objetos de {b}": "Objects in {b}",
  "El bucket está vacío.": "The bucket is empty.",
  "No hay servicios de Cloud Run.": "There are no Cloud Run services.",
  "Autenticación": "Authentication",
  "Permitir no autenticadas": "Allow unauthenticated",
  "Requiere autenticación": "Require authentication",
  "Última revisión": "Last revision",
  "Imagen": "Image",
  "Desplegar contenedor": "Deploy container",
  "Crear un servicio": "Create a service",
  "Desplegar en Cloud Run": "Deploy to Cloud Run",
  "Nombre del servicio": "Service name",
  "URL de la imagen del contenedor": "Container image URL",
  "Permitir invocaciones no autenticadas": "Allow unauthenticated invocations",
  "Cualquiera en internet podrá llamar al servicio.": "Anyone on the internet will be able to call the service.",
  "Número mínimo de instancias": "Minimum number of instances",
  "Número máximo de instancias": "Maximum number of instances",
  "Eliminar servicio de Cloud Run": "Delete Cloud Run service",
  "¿Eliminar los servicios?": "Delete services?",
  "Sus URL dejarán de responder.": "Their URLs will stop responding.",
  "No hay instancias de Cloud SQL.": "There are no Cloud SQL instances.",
  "ID de instancia": "Instance ID",
  "IP pública": "Public IP",
  "IP privada": "Private IP",
  "Alta disponibilidad": "High availability",
  "Sí (regional)": "Yes (regional)",
  "No (zonal)": "No (zonal)",
  "Copias de seguridad": "Backups",
  "Activadas": "On",
  "Desactivadas": "Off",
  "Crear una instancia de Cloud SQL": "Create a Cloud SQL instance",
  "Crear instancia de Cloud SQL": "Create Cloud SQL instance",
  "Versión de la base de datos": "Database version",
  "Alta disponibilidad (varias zonas)": "High availability (multiple zones)",
  "Duplica el coste; sobrevive a la caída de una zona.": "Doubles the cost; survives a zone outage.",
  "Reiniciar": "Restart",
  "Reiniciar Cloud SQL": "Restart Cloud SQL",
  "Eliminar instancia de Cloud SQL": "Delete Cloud SQL instance",
  "Se perderán las bases de datos y sus copias de seguridad.": "The databases and their backups will be lost.",
  "Temas": "Topics",
  "No hay temas.": "There are no topics.",
  "ID del tema": "Topic ID",
  "Suscripciones": "Subscriptions",
  "Mensajes publicados": "Published messages",
  "Crear tema": "Create topic",
  "Crear un tema": "Create a topic",
  "Crear tema de Pub/Sub": "Create Pub/Sub topic",
  "Añadir una suscripción predeterminada": "Add a default subscription",
  "Publicar mensaje": "Publish message",
  "Eliminar tema": "Delete topic",
  "¿Eliminar los temas?": "Delete topics?",
  "Sus suscripciones dejarán de recibir mensajes.": "Their subscriptions will stop receiving messages.",
  "Suscripciones de Pub/Sub": "Pub/Sub subscriptions",
  "No hay suscripciones.": "There are no subscriptions.",
  "ID de la suscripción": "Subscription ID",
  "Tema": "Topic",
  "Tipo de entrega": "Delivery type",
  "Push": "Push",
  "Pull": "Pull",
  "Plazo de confirmación": "Acknowledgement deadline",
  "Mensajes sin confirmar": "Unacked messages",
  "Tema de mensajes fallidos": "Dead-letter topic",
  "Crear suscripción": "Create subscription",
  "Crear una suscripción": "Create a subscription",
  "Plazo de confirmación (s)": "Acknowledgement deadline (s)",
  "Extraer mensajes": "Pull messages",
  "Eliminar suscripción": "Delete subscription",
  "¿Eliminar las suscripciones?": "Delete subscriptions?",
  "Los mensajes pendientes se perderán.": "Pending messages will be lost.",
  "BigQuery: conjuntos de datos": "BigQuery: datasets",
  "No hay conjuntos de datos.": "There are no datasets.",
  "ID": "ID",
  "Tablas": "Tables",
  "Público": "Public",
  "Crear conjunto de datos": "Create dataset",
  "Crear un conjunto de datos": "Create a dataset",
  "ID del conjunto de datos": "Dataset ID",
  "Letras, números y guiones bajos.": "Letters, numbers and underscores.",
  "Eliminar conjunto de datos": "Delete dataset",
  "¿Eliminar los conjuntos de datos?": "Delete datasets?",
  "Se borrarán con todas sus tablas.": "They will be deleted with all their tables.",
  "Tablas de BigQuery": "BigQuery tables",
  "No hay tablas.": "There are no tables.",
  "Tabla": "Table",
  "Filas": "Rows",
  "Partición": "Partition",
  "Consultar": "Query",
  "Consulta": "Query",
  "Clústeres de Kubernetes": "Kubernetes clusters",
  "No hay clústeres.": "There are no clusters.",
  "Estándar": "Standard",
  "Nodos": "Nodes",
  "gestionados": "managed",
  "Canal de versiones": "Release channel",
  "Nodos privados": "Private nodes",
  "Conectar con el clúster": "Connect to the cluster",
  "Crear clúster": "Create cluster",
  "Crear un clúster": "Create a cluster",
  "Crear clúster de GKE": "Create GKE cluster",
  "Autopilot (Google gestiona los nodos)": "Autopilot (Google manages the nodes)",
  "Estándar (tú gestionas los nodos)": "Standard (you manage the nodes)",
  "Número de nodos": "Number of nodes",
  "Tipo de máquina de los nodos": "Node machine type",
  "Eliminar clúster": "Delete cluster",
  "¿Eliminar los clústeres?": "Delete clusters?",
  "Se borrarán con todas sus cargas de trabajo.": "They will be deleted with all their workloads.",
  "Cargas de trabajo (pods)": "Workloads (pods)",
  "Pods de los clústeres": "Cluster pods",
  "No hay pods. Despliega con kubectl apply -f desde la terminal.": "There are no pods. Deploy with kubectl apply -f from the terminal.",
  "Espacio de nombres": "Namespace",
  "Clúster": "Cluster",
  "Listo": "Ready",
  "Reinicios": "Restarts",
  "Motivo": "Reason",
  "Guarda contraseñas y claves fuera del código. Las aplicaciones leen el valor con el rol secretAccessor.": "Keep passwords and keys out of the code. Applications read the value with the secretAccessor role.",
  "No hay secretos.": "There are no secrets.",
  "Replicación": "Replication",
  "Cifrado": "Encryption",
  "Clave gestionada por el cliente": "Customer-managed key",
  "Gestionado por Google": "Google-managed",
  "Nueva versión": "New version",
  "Añadir versión": "Add version",
  "Crear secreto": "Create secret",
  "Crear un secreto": "Create a secret",
  "Valor del secreto": "Secret value",
  "En la terminal se ve el valor: en un proyecto real usa un archivo (--data-file=ruta).": "The value is visible in the terminal: in a real project use a file (--data-file=path).",
  "Eliminar secreto": "Delete secret",
  "¿Eliminar los secretos?": "Delete secrets?",
  "Las aplicaciones que los lean empezarán a fallar.": "Applications that read them will start failing.",
  "Añadir una versión a {s}": "Add a version to {s}",
  "Añadir versión del secreto": "Add secret version",
  "Filtrar APIs": "Filter APIs",
  "APIs del proyecto": "Project APIs",
  "Ninguna API coincide.": "No API matches.",
  "Servicio": "Service",
  "Habilitar API": "Enable API",
  "Habilitar una API": "Enable an API",
  "Inhabilitar API": "Disable API",
  "¿Inhabilitar las APIs?": "Disable APIs?",
  "Los recursos y aplicaciones que las usan dejarán de funcionar.": "The resources and applications that use them will stop working.",
  "En ejecución": "Running",
  "Detenido": "Stopped",
  "Filtrar": "Filter",
  "Introduce el nombre o el valor de una propiedad": "Enter property name or value",
  "Filtrar {what}": "Filter {what}",
  "Seleccionar todo": "Select all",
  "Seleccionar {name}": "Select {name}",
  "Ninguna fila coincide con el filtro.": "No rows match the filter.",
  "Copiado": "Copied",
  "Copiar": "Copy",
  "Ocultar el código equivalente": "Hide equivalent code",
  "Código equivalente": "Equivalent code",
  "Ejecutando…": "Running…",
  "Cancelar": "Cancel",
  "Línea de comandos": "Command line",
  "Esto es lo que se ejecutará en Cloud Shell al pulsar «{b}».": "This is what will run in Cloud Shell when you press \"{b}\".",
  "Pegar en la terminal": "Paste into the terminal",
  "Buscar laboratorios, habilidades y servicios": "Search labs, skills and services",
  "Buscar laboratorios": "Search labs",
  "Cuenta: {name}": "Account: {name}",
  "Cuenta": "Account",
  "Aprende Google Cloud en su propia consola": "Learn Google Cloud in its own console",
  "Explorador": "Explorer",
  "Ticket": "Ticket",
  "Entrega": "Submission",
  "Ocultar las instrucciones": "Hide the instructions",
  "Panel del laboratorio": "Lab panel",
  "Trabaja en la consola o en Cloud Shell: cada botón de la consola ejecuta su comando abajo. Prueba": "Work in the console or in Cloud Shell: every console button runs its command below. Try",
  "y": "and",
  "Cuando termines, envía el laboratorio para que se evalúe.": "When you're done, submit the lab for grading.",
  "Tu proyecto de Cloud Platform en esta sesión es": "Your Cloud Platform project in this session is set to",
  "Lo que hagas en la consola de arriba también se ejecuta aquí.": "What you do in the console above also runs here.",
  "Informes": "Reports",
  "Network Intelligence Center": "Network Intelligence Center",
  "Topología de red": "Network Topology",
  "Explorador de registros": "Logs Explorer",
  "Explorador de métricas": "Metrics explorer",
  "Registro de actividad": "Activity log",
  "Volver al panel de Cloud Mastery": "Back to the Cloud Mastery dashboard",
  "Instrucciones del laboratorio": "Lab instructions",
  "Arrastra para cambiar el tamaño": "Drag to resize",
  "Editor": "Editor",
  "Abrir editor": "Open Editor",
  "Abrir terminal": "Open Terminal",
  "Restaurar": "Restore",
  "Minimizar": "Minimize",
  "Maximizar": "Maximize",
  "Leer en Cloud Shell": "Read in Cloud Shell",
  "Leer registros": "Read logs",
  "Todas las gravedades": "All severities",
  "Una condición por línea (se combinan con AND). Ctrl+Intro ejecuta la consulta.": "One condition per line (combined with AND). Ctrl+Enter runs the query.",
  "Resultados de la consulta": "Query results",
  "{n} entradas": "{n} entries",
  "Entradas de registro": "Log entries",
  "Marca de tiempo": "Timestamp",
  "Resumen": "Summary",
  "Mínimo {a}, máximo {b}": "Minimum {a}, maximum {b}",
  "Métrica": "Metric",
  "Todas las métricas": "All metrics",
  "Políticas de alertas": "Alerting policies",
  "No hay políticas de alertas. Créalas con gcloud alpha monitoring policies create.": "There are no alerting policies. Create them with gcloud alpha monitoring policies create.",
  "Condición": "Condition",
  "Informes de facturación": "Billing reports",
  "Previsión de coste mensual": "Monthly cost forecast",
  "Estimación con los recursos actuales del proyecto {p}.": "Estimate with the current resources of project {p}.",
  "Servicios con coste": "Services with cost",
  "Coste por servicio": "Cost by service",
  "Todavía no hay costes.": "No costs yet.",
  "Detalle por SKU": "Breakdown by SKU",
  "Coste por recurso y SKU": "Cost by resource and SKU",
  "Recursos del proyecto y cómo se conectan; las conexiones rotas aparecen marcadas.": "Project resources and how they connect; broken connections are marked.",
  "Todo lo que se ha ejecutado en este proyecto, desde la consola o desde Cloud Shell.": "Everything run in this project, from the console or from Cloud Shell.",
  "Todavía no hay actividad.": "No activity yet.",
  "Error": "Error",
};
