// English translations of the Spanish interface texts (t("…") keys).
// `npm run check:i18n` fails when a key is missing.

export const en: Record<string, string> = {
  "Éxito al primer intento": "First-attempt success",
  "Dependencia de pistas": "Hint dependency",
  "Intentos hasta el dominio": "Retries to mastery",
  "Retención a 7 días": "Retention 7d",
  "Retención a 30 días": "Retention 30d",
  "Tasa de causa raíz en incidentes": "Incident root-cause rate",
  "Tasa de aprobado en proyectos finales": "Capstone pass rate",
  "Cobertura de habilidades": "Skill coverage",
  "Aprovisionamiento p95": "Provisioning p95",
  "Tasa de error del evaluador": "Grader error rate",
  "Laboratorios con corrección automática": "Auto-graded labs",
  "Tasa de fallos de infraestructura": "Infra failure rate",
  "Consola del instructor": "Instructor console",
  "Clase": "Class",
  "Todo el alumnado": "All learners",
  "Nombre de la nueva clase": "New class name",
  "Crear clase": "Create class",
  "KPI de aprendizaje": "Learning KPIs",
  "{n} alumnos activos · {a} intentos": "{n} active learners · {a} attempts",
  "Valor": "Value",
  "Objetivo": "Target",
  "Analítica de la clase": "Class analytics",
  "correo del alumno": "learner email",
  "Añadir alumno": "Add learner",
  "Dominio del equipo por rama": "Team branch mastery",
  "Alumnado": "Learners",
  "Nombre": "Name",
  "Nivel": "Level",
  "Mejor preparación": "Best readiness",
  "Selecciona una clase para ver su alumnado y el mapa de calor de habilidades del equipo.": "Select a class to see its learners and team skill heatmap.",
  "Calibración de dificultad por laboratorio": "Per-lab difficulty calibration",
  "Pool de proyectos reales de GCP (F2)": "Real-GCP project pool (F2)",
  "Controlador:": "Driver:",
  "Ejecutar la limpieza ahora": "Run janitor now",
  "No hay pool de sandboxes configurado; los laboratorios se ejecutan en el simulador y los emuladores.": "No sandbox pool configured; labs run on the simulator and emulators.",
  "Salud del contenido": "Content health",
  "{n} laboratorios cargados · {p} problemas": "{n} labs loaded · {p} problems",
  "Todo el contenido es válido.": "All content validates.",
  "Tipos de fallo: {list}": "Fault types: {list}",
  "Catálogo de laboratorios": "Lab catalog",
  "Ruta": "Track",
  "Todas las rutas": "All tracks",
  "Buscar laboratorios o habilidades…": "Search labs or skills…",
  "Buscar": "Search",
  "{n} laboratorios": "{n} labs",
  "día {n}": "day {n}",
  "dificultad {n} de 5": "difficulty {n} of 5",
  "¿Empezar de nuevo? Se perderá la historia de tu empresa.": "Start over? Your company's history will be lost.",
  "Cargando…": "Loading…",
  "Únete a {name}": "Join {name}",
  "Eres la nueva persona de ingeniería cloud en {name}. Su entorno de Google Cloud persiste entre misiones: lo que construyes se queda, lo que dejas inseguro o sin copia de seguridad vuelve como incidentes, y la disponibilidad, la postura de seguridad, el coste y la satisfacción de las partes interesadas son responsabilidad tuya.": "You are the new cloud engineer at {name}. Its Google Cloud estate persists between missions: what you build stays, what you leave insecure or unbacked-up comes back as incidents, and the company's availability, security posture, cost and stakeholder satisfaction are yours to look after.",
  "Proyectos": "Projects",
  "Empezar el día 1": "Start day 1",
  "{name} — día {day}": "{name} — day {day}",
  "Empezar de nuevo": "Start over",
  "Disponibilidad": "Availability",
  "Postura de seguridad": "Security posture",
  "Coste mensual": "Monthly cost",
  "Satisfacción de las partes interesadas": "Stakeholder satisfaction",
  "Consecuencias abiertas": "Open consequences",
  "Responder": "Respond",
  "Misiones": "Missions",
  "incidente": "incident",
  "hecha": "done",
  "Reanudar": "Resume",
  "Empezar": "Start",
  "bloqueada": "locked",
  "Diario": "Journal",
  "Día {n}": "Day {n}",
  "Nada todavía.": "Nothing yet.",
  "Personas": "People",
  "No hay nada en cola: elige cualquier laboratorio del catálogo.": "Nothing queued: pick any lab from the catalog.",
  "Hola de nuevo, {name}": "Welcome back, {name}",
  "Descargar expediente firmado": "Download signed transcript",
  "{xp} XP · {bonus} de bonificación · racha de {streak} días": "{xp} XP · {bonus} bonus · {streak}-day streak",
  "Etapa profesional": "Career stage",
  "Siguiente:": "Next:",
  "Autonomía": "Autonomy",
  "Laboratorios en curso": "Labs in progress",
  "empezado el {date}": "started {date}",
  "Plan adaptativo": "Adaptive plan",
  "Recomendaciones de la ruta": "Track recommendations",
  "Dimensiones de competencia": "Competence dimensions",
  "{pct}% · {n} evid.": "{pct}% · {n} evid.",
  "Céntrate ahora en: {list}": "Focus now on: {list}",
  "Preparación para certificaciones": "Certification readiness",
  "Retención": "Retention",
  "Habilidad": "Skill",
  "Recuerdo": "Recall",
  "Repaso": "Review",
  "toca repasar": "review due",
  "Supera laboratorios sin pistas para empezar a construir memoria duradera.": "Pass labs without hints to start building durable memory.",
  "Errores recurrentes": "Recurring errors",
  "Habilidades": "Skills",
  "Dominio": "Mastery",
  "dominada": "mastered",
  "Todavía no hay habilidades medidas.": "No skills measured yet.",
  "Especializaciones": "Specializations",
  "completada": "completed",
  "Falta: {list}": "Missing: {list}",
  "Insignias": "Badges",
  "Aún ninguna.": "None yet.",
  "Generador de incidentes": "Incident generator",
  "Los incidentes se componen a partir de una biblioteca de fallos: un sistema, uno o varios modos de fallo, un contexto de negocio y una dificultad. Con más dificultad los tickets son vagos o engañosos, se acumulan varios fallos y el modo producción activa una sala de crisis P1. Nunca verás qué fallo se ha inyectado.": "Incidents are composed from a failure library: a system, one or more failure modes, a business context and a difficulty. At higher difficulty tickets get vague or misleading, several failures stack, and production mode runs a P1 war room. You never see which failure was injected.",
  "Sistema": "System",
  "Síntoma": "Symptom",
  "Cualquiera (sorpréndeme)": "Any (surprise me)",
  "Contexto de negocio": "Business context",
  "Aleatorio": "Random",
  "Dificultad: {n}": "Difficulty: {n}",
  "Modo": "Mode",
  "Ticket estándar": "Standard ticket",
  "Producción (sala de crisis P1)": "Production (P1 war room)",
  "Problema desconocido (solo se conoce el impacto)": "Unknown problem (only the impact is known)",
  "Preparando el entorno…": "Building the environment…",
  "Generar incidente": "Generate incident",
  "Grafo de síntomas": "Symptom graph",
  "Dónde buscar para cada síntoma, capa por capa.": "Where to look for each symptom, layer by layer.",
  "Objetivos": "Objectives",
  "Restricciones": "Constraints",
  "Cómo se te evaluará": "How you will be graded",
  "crítico": "critical",
  "{n} ptos.": "{n} pts",
  "Fidelidad": "Fidelity",
  "F0 — simulador": "F0 — simulator",
  "F1 — emuladores": "F1 — emulators",
  "F2 — proyecto real de GCP": "F2 — real GCP project",
  "Empezar laboratorio": "Start lab",
  "Este laboratorio no tiene ticket. Usa la terminal y los objetivos de la izquierda.": "This lab has no ticket. Use the terminal and the objectives on the left.",
  "Impacto:": "Impact:",
  "Abierto por {who}": "Opened by {who}",
  "servicio {name}": "{name} service",
  "público": "public",
  "Trabaja el ticket desde la terminal:": "Work the ticket from the terminal:",
  "nombre": "name",
  "pregunta": "question",
  "Conversaciones": "Conversations",
  "Tú → {who}:": "You → {who}:",
  "Consulta de registros": "Log query",
  "Ejecutar consulta": "Run query",
  "Hora": "Time",
  "Gravedad": "Severity",
  "Recurso": "Resource",
  "Mensaje": "Message",
  "por": "by",
  "Ninguna entrada coincide.": "No entries match.",
  "Guardado {file}": "Saved {file}",
  "archivo nuevo (p. ej. main.tf)": "new file (e.g. main.tf)",
  "Nombre del archivo nuevo": "New file name",
  "Guardar": "Save",
  "Elige un archivo o crea uno. Los archivos se comparten con la terminal": "Pick a file or create one. Files are shared with the terminal",
  "Aún no hay nada aquí.": "Nothing here yet.",
  "Todavía no hay recursos.": "No resources yet.",
  "Aún no hay métricas. Aparecen a medida que avanza el tiempo simulado.": "No metrics yet. They appear as simulated time passes.",
  "/ mes (estimación)": "/ month (estimate)",
  "€/mes": "€/month",
  "Comandos que has ejecutado, con su salida": "Commands you ran, with their output",
  "Comando": "Command",
  "Código": "Code",
  "salida": "output",
  "Superado": "Passed",
  "Aún no superado": "Not passed yet",
  "Ha fallado un criterio crítico.": "A critical criterion failed.",
  "de bonificación": "bonus",
  "Cómo has trabajado": "How you worked",
  "Cambios antes de reunir evidencias:": "Changes before gathering evidence:",
  "Restricciones incumplidas:": "Constraints violated:",
  "Mentor": "Mentor",
  "Revisión del post-mortem": "Post-mortem review",
  "Día {n}.": "Day {n}.",
  "Quedan {n} riesgo(s) latente(s) en el entorno…": "{n} latent risk(s) remain in the estate…",
  "Ningún riesgo latente nuevo.": "No new latent risks.",
  "Volver a la empresa →": "Back to the company →",
  "Panel": "Dashboard",
  "Más laboratorios": "More labs",
  "¿Enviar para evaluar? El entorno se cerrará.": "Submit for grading? The environment will be closed.",
  "¿Abandonar este laboratorio?": "Abandon this lab?",
  "Enunciado y entrega": "Brief and submission",
  "proyecto": "project",
  "Cronología": "Timeline",
  "Instrucciones": "Instructions",
  "Ayuda": "Help",
  "Prueba": "Try",
  "recurso": "resource",
  "para ver la cadena causal,": "to see the causal chain,",
  "para explorar consecuencias y": "to explore consequences and",
  "para ver los comandos.": "to list the commands.",
  "Pista (quedan {n})": "Hint ({n} left)",
  "Comprobar": "Check",
  "Evidencias": "Evidence",
  "Preguntas": "Questions",
  "Justifica tu elección": "Justify your choice",
  "Enviar": "Submit",
  "Abandonar": "Abandon",
  "La sesión caduca a las {time}.": "The session expires at {time}.",
  "Modo lector de pantalla para la terminal": "Screen-reader mode for the terminal",
  "Escribe 'help' para ver los comandos.": "Type 'help' for the list of commands.",
  "Vistas del entorno": "Environment views",
  "Actualizar vistas": "Refresh views",
  "Esta sesión está en estado «{status}».": "This session is {status}.",
  "Empezar un intento nuevo →": "Start a new attempt →",
  "Liga semanal": "Weekly league",
  "Las ligas son voluntarias y ordenan la XP de esta semana ponderada por dificultad: los laboratorios difíciles cuentan más que repetir los fáciles.": "Leagues are opt-in and rank this week's XP weighted by difficulty, so hard labs count more than grinding easy ones.",
  "Liga {name}": "League {name}",
  "Salir de la clasificación": "Leave leaderboard",
  "Unirme a la clasificación": "Join leaderboard",
  "Puntos": "Points",
  "Nadie ha puntuado en esta liga esta semana.": "No one has scored in this league this week.",
  "Aprende Google Cloud haciendo el trabajo: construye, rompe, diagnostica y repara sistemas en un simulador determinista, gestiona una empresa persistente, atiende tickets de personas que no conocen la causa raíz y da el salto a entornos reales.": "Learn Google Cloud by doing the job: build, break, diagnose and fix systems in a deterministic simulator, run a persistent company, work tickets from people who don't know the root cause, and graduate to real environments.",
  "Flujos reales con gcloud, gsutil, bq, kubectl y terraform": "Real gcloud, gsutil, bq, kubectl and terraform workflows",
  "Incidentes generados a partir de una biblioteca de fallos, salas de crisis P1 y experimentos de caos": "Incidents generated from a failure library, P1 war rooms and chaos experiments",
  "Evaluación del proceso: diagnóstico, seguridad, coste, riesgo y comunicación": "Process grading: diagnosis, security, cost, risk and communication",
  "Nueve dimensiones de competencia, retención espaciada y una escalera de autonomía": "Nine competence dimensions, spaced retention and an autonomy ladder",
  "Etapas de carrera de becario a arquitecto con expedientes verificables": "Career stages from intern to architect with verifiable transcripts",
  "Iniciar sesión": "Sign in",
  "Crear cuenta": "Create account",
  "Correo electrónico": "Email",
  "Nombre visible": "Display name",
  "Contraseña": "Password",
  "Entrar con Google Workspace (si está configurado)": "Sign in with Google Workspace (if configured)",
  "Verificar el expediente de un alumno": "Verify a learner's transcript",
  "Grafo de habilidades": "Skill graph",
  "Las habilidades se desbloquean en orden de dependencias. Verde es dominada (≥80), ámbar está en progreso.": "Skills unlock in dependency order. Green is mastered (≥80), amber is in progress.",
  "Rama": "Branch",
  "Todas las ramas ({n} habilidades)": "All branches ({n} skills)",
  "Dominio por rama": "Branch mastery",
  "Trayectoria profesional": "Career path",
  "Etapa {n}": "Stage {n}",
  "Proyectos finales:": "Capstones:",
  "Verificar un expediente": "Verify a transcript",
  "El alumnado puede descargar un expediente firmado con sus competencias, su etapa profesional y los proyectos finales completados. Pégalo aquí para comprobar que lo emitió esta plataforma y que no se ha modificado.": "Learners can download a signed transcript of their competences, career stage and completed capstones. Paste it here to check that it was issued by this platform and has not been modified.",
  "{ … JSON del expediente … }": "{ … transcript JSON … }",
  "Verificar": "Verify",
  "Volver": "Back",
  "✓ Expediente válido": "✓ Valid transcript",
  "✗ Firma no válida": "✗ Invalid signature",
  "etapa profesional": "career stage",
  "emitido el {date}": "issued {date}",
  "Autonomía: {a} · {n} laboratorios superados · especializaciones: {s}": "Autonomy: {a} · {n} labs passed · specializations: {s}",
  "ninguna": "none",
  "Laboratorios": "Labs",
  "Incidentes": "Incidents",
  "Empresa": "Company",
  "Ligas": "Leagues",
  "Idioma": "Language",
  "Principal": "Main",
  "Saltar al contenido": "Skip to content",
  "Instructor": "Instructor",
  "Cerrar sesión": "Sign out",
  "…": "…",
  "siguiente": "next",
  "refuerzo": "remediation",
  "repetición": "retest",
  "simulacro": "mock exam",
  "repaso": "review",
  "incidente sorpresa": "surprise incident",
  "dimensión": "dimension",
  "nuevo": "new",
  "Conocimiento": "Knowledge",
  "Ejecución": "Execution",
  "Resolución de problemas": "Troubleshooting",
  "Arquitectura": "Architecture",
  "Seguridad": "Security",
  "Coste": "Cost",
  "Operaciones": "Operations",
  "básico": "basic",
  "intermedio": "intermediate",
  "avanzado": "advanced",
  "profesional": "professional",
  "guiado": "guided",
  "reto": "challenge",
  "test": "quiz",
  "proyecto final": "capstone",
  "jefe final": "boss",
  "caso práctico": "case study",
  "entrevista": "interview",
  "producción": "production",
  "problema desconocido": "unknown problem",
  "carrera": "career",
  "arquitectura": "architecture",
  "aprendizaje": "learn",
  "laboratorio": "lab",
  "ticket": "ticket",
  "consola": "console",
  "topología": "topology",
  "registros": "logs",
  "métricas": "metrics",
  "IAM": "IAM",
  "coste": "cost",
  "archivos": "files",
  "historial": "history",
  "resolución": "resolution",
  "diagnóstico": "diagnosis",
  "seguridad": "security",
  "eficiencia": "efficiency",
  "riesgo": "risk",
  "comunicación": "communication",
  "documentación": "documentation",
  "autonomía": "autonomy",
  "NUEVO": "NEW",
  "EN CURSO": "IN PROGRESS",
  "RESUELTO": "RESOLVED",
  "ESCALADO": "ESCALATED",
  "desarrollo": "developer",
  "finanzas": "finance",
  "dirección": "manager",
  "cliente": "customer",
  "SRE": "SRE",
  "operaciones": "ops",
  "Causa raíz": "Root cause",
  "Corrección": "Fix",
  "Verificación": "Verification",
  "Prevención": "Prevention",
  "Post-mortem": "Post-mortem",
  "Explicación": "Explanation",
  "Decisiones de diseño": "Design decisions",
  "Plan de despliegue": "Rollout plan",
  "funcional": "functional",
  "estado": "state",
  "fiabilidad": "reliability",
  "evidencia": "evidence",
  "preguntas": "quiz",
  "pista": "hint",
  "pista parcial": "partial hint",
  "solución": "solution",
  "No modifiques {name} (pertenece a otro equipo)": "Do not modify {name} (it belongs to another team)",
  "Sin interrupción del servicio": "No downtime",
  "Nada público (sin allUsers ni allAuthenticatedUsers)": "Nothing public (no allUsers or allAuthenticatedUsers)",
  "Sin roles básicos (Owner, Editor, Viewer)": "No basic roles (Owner, Editor, Viewer)",
  "No borres recursos": "Do not delete resources",
  "DNS": "DNS",
  "balanceador de carga": "load balancer",
  "salud de los backends": "backend health",
  "cortafuegos": "firewall",
  "tiempos de espera": "timeouts",
  "aplicación": "application",
  "preparación de pods (readiness)": "pod readiness",
  "carga de trabajo de Kubernetes": "Kubernetes workload",
  "Service de Kubernetes": "Kubernetes Service",
  "versión desplegada": "release",
  "configuración": "configuration",
  "identidad y permisos": "identity and permissions",
  "camino de red": "network path",
  "base de datos": "database",
  "cuotas": "quotas",
  "capacidad": "capacity",
  "pool de conexiones": "connection pool",
  "autoescalado": "autoscaling",
  "permisos de almacenamiento": "storage permissions",
  "permisos del servicio": "service permissions",
  "políticas de organización": "organization policies",
  "cómputo": "compute",
  "almacenamiento": "storage",
  "tráfico de salida": "egress traffic",
  "procesamiento de datos": "data processing",
  "recursos ociosos": "idle resources",
  "etiquetas de red": "network tags",
  "comprobación de estado": "health check",
  "Cargando el editor…": "Loading editor…",
  "sin datos": "no data",
  "Terminal de Cloud Shell. Escribe comandos y pulsa Intro.": "Cloud Shell terminal. Type commands and press Enter.",
};
