package tutor

// res describes a kind of Google Cloud resource for the tutor: where it lives
// in the console and what it is, in Spanish and English.
type res struct {
	page           string // console page id ("" = Cloud Shell only)
	pathES, pathEN string // console breadcrumb
	oneES, oneEN   string // singular with article
	manyES, manyEN string // plural with article
	whatES, whatEN string // one-sentence concept
}

// resources is keyed by the gcloud command group (words before the verb).
var resources = map[string]res{
	"compute instances": {"vm", "Compute Engine › Instancias de VM", "Compute Engine › VM instances", "la VM", "the VM", "las VMs", "the VMs",
		"Una VM es un servidor virtual: eliges máquina, disco, red y cuenta de servicio.", "A VM is a virtual server: you choose machine type, disk, network and service account."},
	"compute firewall-rules": {"firewall", "Red de VPC › Cortafuegos", "VPC network › Firewall", "la regla de cortafuegos", "the firewall rule", "las reglas de cortafuegos", "the firewall rules",
		"Las reglas de cortafuegos deciden qué tráfico puede llegar a las VMs de una red; por defecto se bloquea todo lo que entra.", "Firewall rules decide which traffic may reach the VMs of a network; by default all ingress is blocked."},
	"compute networks": {"vpc", "Red de VPC › Redes de VPC", "VPC network › VPC networks", "la red de VPC", "the VPC network", "las redes de VPC", "the VPC networks",
		"Una red de VPC es tu red privada en Google Cloud; las subredes de cada región cuelgan de ella.", "A VPC network is your private network in Google Cloud; each region's subnets hang from it."},
	"compute networks subnets": {"vpc", "Red de VPC › Redes de VPC › Subredes", "VPC network › VPC networks › Subnets", "la subred", "the subnet", "las subredes", "the subnets",
		"Una subred es un rango de IPs privadas de una región dentro de la VPC.", "A subnet is a range of private IPs in one region inside the VPC."},
	"compute networks peerings": {"peering", "Red de VPC › Emparejamiento de redes de VPC", "VPC network › VPC network peering", "el emparejamiento", "the peering", "los emparejamientos", "the peerings",
		"El emparejamiento conecta dos VPC por IP privada; hay que crearlo en los dos lados y no es transitivo.", "Peering connects two VPCs over private IP; it must exist on both sides and is not transitive."},
	"compute addresses": {"addresses", "Red de VPC › Direcciones IP", "VPC network › IP addresses", "la dirección IP", "the IP address", "las direcciones IP", "the IP addresses",
		"Reserva una IP para que no cambie aunque se recree el recurso que la usa.", "Reserves an IP so it does not change when the resource using it is recreated."},
	"compute routes": {"routes", "Red de VPC › Rutas", "VPC network › Routes", "la ruta", "the route", "las rutas", "the routes",
		"Las rutas dicen por dónde sale el tráfico de la VPC.", "Routes say where traffic leaves the VPC through."},
	"compute routers": {"nat", "Servicios de red › Cloud NAT", "Network services › Cloud NAT", "el Cloud Router", "the Cloud Router", "los Cloud Routers", "the Cloud Routers",
		"Cloud Router gestiona rutas dinámicas y es la base de Cloud NAT y de la VPN.", "Cloud Router manages dynamic routes and is the base of Cloud NAT and VPN."},
	"compute routers nats": {"nat", "Servicios de red › Cloud NAT", "Network services › Cloud NAT", "la pasarela NAT", "the NAT gateway", "las pasarelas NAT", "the NAT gateways",
		"Cloud NAT deja que VMs sin IP pública salgan a internet sin quedar expuestas.", "Cloud NAT lets VMs without a public IP reach the internet without being exposed."},
	"compute backend-services": {"lb", "Servicios de red › Balanceo de carga", "Network services › Load balancing", "el servicio de backend", "the backend service", "los servicios de backend", "the backend services",
		"El servicio de backend reparte las peticiones del balanceador entre los grupos de instancias sanos.", "The backend service spreads load-balancer requests over the healthy instance groups."},
	"compute health-checks": {"healthchecks", "Compute Engine › Comprobaciones de estado", "Compute Engine › Health checks", "la comprobación de estado", "the health check", "las comprobaciones de estado", "the health checks",
		"La comprobación de estado pregunta a cada VM si está sana; el balanceador solo envía tráfico a las sanas.", "The health check asks each VM whether it is healthy; the load balancer only sends traffic to healthy ones."},
	"compute instance-groups": {"groups", "Compute Engine › Grupos de instancias", "Compute Engine › Instance groups", "el grupo de instancias", "the instance group", "los grupos de instancias", "the instance groups",
		"Un grupo de instancias junta VMs iguales para balancear, escalar y repararlas solas.", "An instance group gathers identical VMs to load-balance, scale and heal them automatically."},
	"compute instance-groups managed": {"groups", "Compute Engine › Grupos de instancias", "Compute Engine › Instance groups", "el grupo gestionado", "the managed instance group", "los grupos gestionados", "the managed instance groups",
		"Un grupo gestionado crea VMs a partir de una plantilla, las escala y sustituye las que fallan.", "A managed group creates VMs from a template, scales them and replaces failing ones."},
	"compute instance-templates": {"templates", "Compute Engine › Plantillas de instancia", "Compute Engine › Instance templates", "la plantilla de instancia", "the instance template", "las plantillas de instancia", "the instance templates",
		"Una plantilla es la receta de una VM que usan los grupos gestionados.", "A template is the recipe of a VM that managed groups use."},
	"compute url-maps": {"lb", "Servicios de red › Balanceo de carga", "Network services › Load balancing", "el mapa de URLs", "the URL map", "los mapas de URLs", "the URL maps",
		"El mapa de URLs decide a qué backend va cada ruta o dominio.", "The URL map decides which backend each path or host goes to."},
	"compute target-http-proxies": {"lb", "Servicios de red › Balanceo de carga", "Network services › Load balancing", "el proxy HTTP", "the HTTP proxy", "los proxies HTTP", "the HTTP proxies",
		"El proxy de destino termina las conexiones del cliente y consulta el mapa de URLs.", "The target proxy terminates client connections and consults the URL map."},
	"compute target-https-proxies": {"lb", "Servicios de red › Balanceo de carga", "Network services › Load balancing", "el proxy HTTPS", "the HTTPS proxy", "los proxies HTTPS", "the HTTPS proxies",
		"El proxy HTTPS termina TLS con tu certificado.", "The HTTPS proxy terminates TLS with your certificate."},
	"compute forwarding-rules": {"lb", "Servicios de red › Balanceo de carga", "Network services › Load balancing", "la regla de reenvío", "the forwarding rule", "las reglas de reenvío", "the forwarding rules",
		"La regla de reenvío es la IP y el puerto públicos del balanceador (su «frontend»).", "The forwarding rule is the load balancer's public IP and port (its frontend)."},
	"compute network-endpoint-groups": {"lb", "Servicios de red › Balanceo de carga", "Network services › Load balancing", "el NEG", "the NEG", "los NEG", "the NEGs",
		"Un NEG serverless deja poner Cloud Run o Functions detrás de un balanceador.", "A serverless NEG puts Cloud Run or Functions behind a load balancer."},
	"compute security-policies": {"armor", "Servicios de red › Cloud Armor", "Network services › Cloud Armor", "la política de Cloud Armor", "the Cloud Armor policy", "las políticas de Cloud Armor", "the Cloud Armor policies",
		"Cloud Armor filtra peticiones en el borde (IPs, países, ataques) antes de que lleguen a tus backends.", "Cloud Armor filters requests at the edge (IPs, countries, attacks) before they reach your backends."},
	"compute security-policies rules": {"armor", "Servicios de red › Cloud Armor", "Network services › Cloud Armor", "la regla de Cloud Armor", "the Cloud Armor rule", "las reglas de Cloud Armor", "the Cloud Armor rules",
		"Cada regla tiene prioridad (menor número = antes), condición y acción.", "Each rule has a priority (lower number = first), a condition and an action."},
	"compute disks": {"disks", "Compute Engine › Discos", "Compute Engine › Disks", "el disco", "the disk", "los discos", "the disks",
		"Los discos persistentes guardan los datos de las VMs y se cobran aunque la VM esté parada.", "Persistent disks hold VM data and are billed even when the VM is stopped."},
	"compute snapshots": {"snapshots", "Compute Engine › Instantáneas", "Compute Engine › Snapshots", "la instantánea", "the snapshot", "las instantáneas", "the snapshots",
		"Una instantánea es una copia de un disco en un momento dado.", "A snapshot is a point-in-time copy of a disk."},
	"compute vpn-gateways": {"vpn", "Servicios de red › Cloud VPN", "Network services › Cloud VPN", "la pasarela VPN", "the VPN gateway", "las pasarelas VPN", "the VPN gateways",
		"La VPN conecta tu VPC con otra red (por ejemplo, la oficina) cifrando el tráfico por internet.", "VPN connects your VPC to another network (e.g. the office) encrypting traffic over the internet."},
	"compute vpn-tunnels": {"vpn", "Servicios de red › Cloud VPN", "Network services › Cloud VPN", "el túnel VPN", "the VPN tunnel", "los túneles VPN", "the VPN tunnels",
		"Cada túnel une tu pasarela con la del otro extremo.", "Each tunnel joins your gateway with the one at the other end."},
	"container clusters": {"gke", "Kubernetes Engine › Clústeres", "Kubernetes Engine › Clusters", "el clúster de GKE", "the GKE cluster", "los clústeres", "the clusters",
		"GKE es Kubernetes gestionado: Google opera el plano de control y tú despliegas contenedores.", "GKE is managed Kubernetes: Google runs the control plane and you deploy containers."},
	"container node-pools": {"gke", "Kubernetes Engine › Clústeres", "Kubernetes Engine › Clusters", "el grupo de nodos", "the node pool", "los grupos de nodos", "the node pools",
		"Un grupo de nodos son las VMs donde corren los pods; cada grupo puede tener otra máquina.", "A node pool is the VMs where pods run; each pool can use a different machine."},
	"run services": {"run", "Cloud Run › Servicios", "Cloud Run › Services", "el servicio de Cloud Run", "the Cloud Run service", "los servicios de Cloud Run", "the Cloud Run services",
		"Cloud Run ejecuta contenedores sin servidores que gestionar y escala según las peticiones.", "Cloud Run runs containers with no servers to manage and scales with requests."},
	"run": {"run", "Cloud Run › Servicios", "Cloud Run › Services", "el servicio de Cloud Run", "the Cloud Run service", "los servicios de Cloud Run", "the Cloud Run services",
		"Cloud Run ejecuta contenedores sin servidores que gestionar y escala según las peticiones.", "Cloud Run runs containers with no servers to manage and scales with requests."},
	"run revisions": {"run", "Cloud Run › Servicios › Revisiones", "Cloud Run › Services › Revisions", "la revisión", "the revision", "las revisiones", "the revisions",
		"Cada despliegue crea una revisión inmutable; el tráfico se reparte entre revisiones.", "Every deploy creates an immutable revision; traffic is split between revisions."},
	"sql instances": {"sql", "SQL › Instancias", "SQL › Instances", "la instancia de Cloud SQL", "the Cloud SQL instance", "las instancias de Cloud SQL", "the Cloud SQL instances",
		"Cloud SQL es PostgreSQL/MySQL gestionado: Google hace copias, parches y alta disponibilidad.", "Cloud SQL is managed PostgreSQL/MySQL: Google handles backups, patches and high availability."},
	"sql databases": {"sql", "SQL › Instancias › Bases de datos", "SQL › Instances › Databases", "la base de datos", "the database", "las bases de datos", "the databases",
		"Una instancia de Cloud SQL puede tener varias bases de datos.", "A Cloud SQL instance can hold several databases."},
	"sql users": {"sql", "SQL › Instancias › Usuarios", "SQL › Instances › Users", "el usuario de la base de datos", "the database user", "los usuarios", "the users",
		"Los usuarios de la base de datos son distintos de las identidades de IAM.", "Database users are different from IAM identities."},
	"sql backups": {"sql", "SQL › Instancias › Copias de seguridad", "SQL › Instances › Backups", "la copia de seguridad", "the backup", "las copias de seguridad", "the backups",
		"Restaurar una copia sustituye todo lo que hay en la instancia de destino.", "Restoring a backup replaces everything on the target instance."},
	"sql": {"sql", "SQL › Instancias", "SQL › Instances", "la instancia de Cloud SQL", "the Cloud SQL instance", "las instancias de Cloud SQL", "the Cloud SQL instances",
		"La exportación e importación las hace el agente de servicio de Cloud SQL: necesita permiso en el bucket.", "Export and import are done by the Cloud SQL service agent: it needs permission on the bucket."},
	"iam service-accounts": {"sa", "IAM y administración › Cuentas de servicio", "IAM & Admin › Service accounts", "la cuenta de servicio", "the service account", "las cuentas de servicio", "the service accounts",
		"Una cuenta de servicio es la identidad de una aplicación o VM, no de una persona.", "A service account is the identity of an application or VM, not of a person."},
	"iam service-accounts keys": {"sa", "IAM y administración › Cuentas de servicio › Claves", "IAM & Admin › Service accounts › Keys", "la clave de la cuenta de servicio", "the service account key", "las claves", "the keys",
		"Las claves descargables son un riesgo: si se filtran, cualquiera actúa como esa cuenta. Mejor evitarlas.", "Downloadable keys are a risk: if leaked anyone can act as that account. Avoid them."},
	"iam roles": {"roles", "IAM y administración › Roles", "IAM & Admin › Roles", "el rol", "the role", "los roles", "the roles",
		"Un rol es un conjunto de permisos; los personalizados permiten dar solo lo justo.", "A role is a set of permissions; custom roles give just what is needed."},
	"projects": {"iam", "IAM y administración › IAM", "IAM & Admin › IAM", "el proyecto", "the project", "los proyectos", "the projects",
		"En el proyecto se conceden los roles que afectan a todos sus recursos.", "Roles granted on the project affect all of its resources."},
	"storage buckets": {"buckets", "Cloud Storage › Buckets", "Cloud Storage › Buckets", "el bucket", "the bucket", "los buckets", "the buckets",
		"Un bucket guarda archivos (objetos); su nombre es único en todo Google Cloud.", "A bucket stores files (objects); its name is unique across Google Cloud."},
	"storage": {"buckets", "Cloud Storage › Buckets", "Cloud Storage › Buckets", "el objeto", "the object", "los objetos", "the objects",
		"Los objetos son los archivos dentro de un bucket.", "Objects are the files inside a bucket."},
	"pubsub topics": {"pubsub", "Pub/Sub › Temas", "Pub/Sub › Topics", "el tema", "the topic", "los temas", "the topics",
		"Un tema recibe mensajes de los productores y los reparte a sus suscripciones.", "A topic receives messages from producers and fans them out to its subscriptions."},
	"pubsub subscriptions": {"pubsub", "Pub/Sub › Suscripciones", "Pub/Sub › Subscriptions", "la suscripción", "the subscription", "las suscripciones", "the subscriptions",
		"Cada suscripción recibe su propia copia de los mensajes del tema.", "Each subscription gets its own copy of the topic's messages."},
	"logging": {"logs", "Logging › Explorador de registros", "Logging › Logs Explorer", "los registros", "the logs", "los registros", "the logs",
		"Cloud Logging guarda qué pasó (errores, peticiones) y quién hizo qué (registros de auditoría).", "Cloud Logging keeps what happened (errors, requests) and who did what (audit logs)."},
	"logging metrics": {"logmetrics", "Logging › Métricas basadas en registros", "Logging › Log-based metrics", "la métrica basada en registros", "the log-based metric", "las métricas", "the metrics",
		"Una métrica basada en registros cuenta líneas de registro para poder alertar sobre ellas.", "A log-based metric counts log lines so you can alert on them."},
	"logging sinks": {"sinks", "Logging › Enrutador de registros", "Logging › Log router", "el sumidero", "the sink", "los sumideros", "the sinks",
		"Un sumidero copia registros a otro destino (bucket, BigQuery, Pub/Sub) para guardarlos o analizarlos.", "A sink copies logs to another destination (bucket, BigQuery, Pub/Sub) to keep or analyse them."},
	"monitoring policies": {"alerting", "Monitoring › Alertas", "Monitoring › Alerting", "la política de alertas", "the alerting policy", "las políticas de alertas", "the alerting policies",
		"Una política de alertas avisa por un canal cuando una métrica cruza un umbral.", "An alerting policy notifies a channel when a metric crosses a threshold."},
	"monitoring channels": {"alerting", "Monitoring › Alertas › Canales", "Monitoring › Alerting › Channels", "el canal de notificación", "the notification channel", "los canales", "the channels",
		"El canal es a quién se avisa: correo, SMS, Slack…", "The channel is who gets notified: email, SMS, Slack…"},
	"monitoring uptime": {"uptime", "Monitoring › Comprobaciones de disponibilidad", "Monitoring › Uptime checks", "la comprobación de disponibilidad", "the uptime check", "las comprobaciones", "the checks",
		"Una sonda externa que prueba tu URL cada pocos minutos.", "An external probe that tests your URL every few minutes."},
	"secrets": {"secrets", "Seguridad › Secret Manager", "Security › Secret Manager", "el secreto", "the secret", "los secretos", "the secrets",
		"Secret Manager guarda contraseñas y claves fuera del código, con versiones y permisos.", "Secret Manager keeps passwords and keys out of the code, with versions and permissions."},
	"secrets versions": {"secrets", "Seguridad › Secret Manager › Versiones", "Security › Secret Manager › Versions", "la versión del secreto", "the secret version", "las versiones", "the versions",
		"Cada cambio del secreto crea una versión; las apps suelen leer «latest».", "Each change creates a version; apps usually read \"latest\"."},
	"kms keyrings": {"kms", "Seguridad › Gestión de claves", "Security › Key management", "el llavero", "the key ring", "los llaveros", "the key rings",
		"Un llavero agrupa claves de cifrado en una ubicación.", "A key ring groups encryption keys in one location."},
	"kms keys": {"kms", "Seguridad › Gestión de claves", "Security › Key management", "la clave de cifrado", "the encryption key", "las claves", "the keys",
		"Con CMEK los datos se cifran con tu clave; si la desactivas, nadie puede leerlos.", "With CMEK data is encrypted with your key; if you disable it nobody can read the data."},
	"artifacts repositories": {"artifacts", "CI/CD › Artifact Registry", "CI/CD › Artifact Registry", "el repositorio de artefactos", "the artifact repository", "los repositorios", "the repositories",
		"Artifact Registry guarda tus imágenes de contenedor y paquetes.", "Artifact Registry stores your container images and packages."},
	"builds": {"build", "CI/CD › Cloud Build", "CI/CD › Cloud Build", "la compilación", "the build", "las compilaciones", "the builds",
		"Cloud Build ejecuta los pasos de compilación en la nube y publica la imagen.", "Cloud Build runs build steps in the cloud and publishes the image."},
	"builds triggers": {"build", "CI/CD › Cloud Build › Activadores", "CI/CD › Cloud Build › Triggers", "el activador", "the trigger", "los activadores", "the triggers",
		"Un activador lanza una compilación en cada commit o etiqueta.", "A trigger starts a build on every commit or tag."},
	"deploy": {"deploy", "CI/CD › Cloud Deploy", "CI/CD › Cloud Deploy", "el flujo de entrega", "the delivery pipeline", "los flujos", "the pipelines",
		"Cloud Deploy promociona versiones por entornos (staging → prod) con aprobación y vuelta atrás.", "Cloud Deploy promotes releases through environments (staging → prod) with approval and rollback."},
	"deploy releases": {"deploy", "CI/CD › Cloud Deploy", "CI/CD › Cloud Deploy", "la versión", "the release", "las versiones", "the releases",
		"Una versión es una imagen concreta lista para desplegarse en cada destino.", "A release is a concrete image ready to roll out to each target."},
	"dns managed-zones": {"dns", "Servicios de red › Cloud DNS", "Network services › Cloud DNS", "la zona DNS", "the DNS zone", "las zonas DNS", "the DNS zones",
		"Una zona DNS contiene los registros de un dominio.", "A DNS zone holds a domain's records."},
	"dns record-sets": {"dns", "Servicios de red › Cloud DNS", "Network services › Cloud DNS", "el registro DNS", "the DNS record", "los registros DNS", "the DNS records",
		"Un registro A traduce un nombre (www) a una IP.", "An A record translates a name (www) into an IP."},
	"services": {"apis", "APIs y servicios", "APIs & Services", "la API", "the API", "las APIs", "the APIs",
		"Cada servicio de Google Cloud se activa por proyecto antes de poder usarlo.", "Each Google Cloud service must be enabled per project before use."},
	"services vpc-peerings": {"apis", "Red de VPC › Acceso privado a servicios", "VPC network › Private service access", "la conexión privada a servicios", "the private service connection", "las conexiones", "the connections",
		"El acceso privado a servicios deja que Cloud SQL o Memorystore tengan IP privada en tu VPC.", "Private service access gives Cloud SQL or Memorystore a private IP in your VPC."},
	"billing budgets": {"budgets", "Facturación › Presupuestos y alertas", "Billing › Budgets & alerts", "el presupuesto", "the budget", "los presupuestos", "the budgets",
		"Un presupuesto avisa cuando el gasto se acerca a un límite (no lo corta).", "A budget alerts when spend approaches a limit (it does not stop it)."},
	"billing": {"billing", "Facturación › Informes", "Billing › Reports", "la factura", "the bill", "las facturas", "the bills",
		"El informe muestra en qué se va el dinero, por servicio y recurso.", "The report shows where the money goes, per service and resource."},
	"resource-manager org-policies": {"orgpolicies", "IAM y administración › Políticas de organización", "IAM & Admin › Organization policies", "la política de organización", "the organization policy", "las políticas", "the policies",
		"Una política de organización es una barrera que nadie puede saltarse, ni siquiera un Owner.", "An organization policy is a guardrail nobody can bypass, not even an Owner."},
	"org-policies": {"orgpolicies", "IAM y administración › Políticas de organización", "IAM & Admin › Organization policies", "la política de organización", "the organization policy", "las políticas", "the policies",
		"Una política de organización es una barrera que nadie puede saltarse, ni siquiera un Owner.", "An organization policy is a guardrail nobody can bypass, not even an Owner."},
	"scc findings": {"scc", "Seguridad › Security Command Center", "Security › Security Command Center", "el hallazgo", "the finding", "los hallazgos", "the findings",
		"Security Command Center lista configuraciones inseguras detectadas en tus recursos.", "Security Command Center lists insecure configurations detected in your resources."},
	"recommender recommendations": {"scc", "Seguridad › Security Command Center", "Security › Security Command Center", "la recomendación", "the recommendation", "las recomendaciones", "the recommendations",
		"El recomendador sugiere ahorros y reducciones de permisos a partir del uso real.", "The recommender suggests savings and permission reductions from real usage."},
	"ai endpoints": {"vertex", "Vertex AI › Endpoints", "Vertex AI › Endpoints", "el endpoint", "the endpoint", "los endpoints", "the endpoints",
		"Un endpoint sirve predicciones de uno o varios modelos desplegados.", "An endpoint serves predictions from one or more deployed models."},
	"ai models": {"vertex", "Vertex AI › Registro de modelos", "Vertex AI › Model registry", "el modelo", "the model", "los modelos", "the models",
		"El registro de modelos guarda las versiones de tus modelos entrenados.", "The model registry keeps versions of your trained models."},
	"functions": {"functions", "Cloud Functions", "Cloud Functions", "la función", "the function", "las funciones", "the functions",
		"Una función es un trozo de código que se ejecuta ante un evento (HTTP, Pub/Sub, un archivo).", "A function is a piece of code that runs on an event (HTTP, Pub/Sub, a file)."},
	"scheduler jobs": {"scheduler", "Cloud Scheduler", "Cloud Scheduler", "el trabajo programado", "the scheduled job", "los trabajos", "the jobs",
		"Cloud Scheduler es un cron gestionado: llama a una URL o publica en Pub/Sub cuando toca.", "Cloud Scheduler is a managed cron: it calls a URL or publishes to Pub/Sub on schedule."},
	"tasks queues": {"tasks", "Cloud Tasks › Colas", "Cloud Tasks › Queues", "la cola", "the queue", "las colas", "the queues",
		"Cloud Tasks entrega trabajos uno a uno con reintentos y límite de velocidad.", "Cloud Tasks delivers work items one by one with retries and rate limits."},
	"app": {"appengine", "App Engine", "App Engine", "la aplicación de App Engine", "the App Engine app", "las versiones", "the versions",
		"App Engine ejecuta tu app por versiones y reparte el tráfico entre ellas.", "App Engine runs your app as versions and splits traffic between them."},
	"app versions": {"appengine", "App Engine › Versiones", "App Engine › Versions", "la versión", "the version", "las versiones", "the versions",
		"Cada despliegue es una versión; puedes probarla en su propia URL antes de darle tráfico.", "Each deploy is a version; you can test it on its own URL before giving it traffic."},
	"app services": {"appengine", "App Engine › Versiones", "App Engine › Versions", "el servicio de App Engine", "the App Engine service", "los servicios", "the services",
		"El reparto de tráfico decide qué porcentaje recibe cada versión.", "The traffic split decides which percentage each version gets."},
	"redis instances": {"redis", "Memorystore › Redis", "Memorystore › Redis", "la instancia de Redis", "the Redis instance", "las instancias de Redis", "the Redis instances",
		"Memorystore es Redis gestionado; solo tiene IP privada en la red que eliges al crearlo.", "Memorystore is managed Redis; it only has a private IP in the network chosen at creation."},
	"spanner instances": {"spanner", "Spanner › Instancias", "Spanner › Instances", "la instancia de Spanner", "the Spanner instance", "las instancias", "the instances",
		"Spanner es una base de datos relacional que escala en horizontal; se paga por unidades de procesamiento.", "Spanner is a relational database that scales horizontally; you pay per processing unit."},
	"spanner databases": {"spanner", "Spanner › Instancias › Bases de datos", "Spanner › Instances › Databases", "la base de datos de Spanner", "the Spanner database", "las bases de datos", "the databases",
		"El esquema (DDL) se cambia con operaciones aparte de las consultas.", "The schema (DDL) is changed with operations separate from queries."},
	"firestore databases": {"firestore", "Firestore › Bases de datos", "Firestore › Databases", "la base de datos de Firestore", "the Firestore database", "las bases de datos", "the databases",
		"Firestore guarda documentos JSON en colecciones, sin esquema fijo.", "Firestore stores JSON documents in collections, with no fixed schema."},
	"firestore indexes composite": {"firestore", "Firestore › Índices", "Firestore › Indexes", "el índice compuesto", "the composite index", "los índices", "the indexes",
		"Las consultas que filtran por un campo y ordenan por otro necesitan un índice compuesto.", "Queries that filter on one field and sort by another need a composite index."},
	"firestore": {"firestore", "Firestore", "Firestore", "la base de datos de Firestore", "the Firestore database", "las bases de datos", "the databases",
		"Exportar deja una copia de los documentos en Cloud Storage.", "Exporting leaves a copy of the documents in Cloud Storage."},
	"dataflow jobs": {"dataflow", "Dataflow › Trabajos", "Dataflow › Jobs", "el trabajo de Dataflow", "the Dataflow job", "los trabajos", "the jobs",
		"Dataflow procesa datos en lote o en streaming; las plantillas de Google evitan escribir código.", "Dataflow processes data in batch or streaming; Google templates avoid writing code."},
	"dataproc clusters": {"dataproc", "Dataproc › Clústeres", "Dataproc › Clusters", "el clúster de Dataproc", "the Dataproc cluster", "los clústeres", "the clusters",
		"Dataproc es Spark/Hadoop gestionado; se paga mientras el clúster existe.", "Dataproc is managed Spark/Hadoop; you pay while the cluster exists."},
	"dataproc jobs": {"dataproc", "Dataproc › Trabajos", "Dataproc › Jobs", "el trabajo de Spark", "the Spark job", "los trabajos", "the jobs",
		"Los trabajos se envían a un clúster en marcha.", "Jobs are submitted to a running cluster."},
	"composer environments": {"composer", "Composer › Entornos", "Composer › Environments", "el entorno de Composer", "the Composer environment", "los entornos", "the environments",
		"Composer es Airflow gestionado para orquestar tareas con DAGs.", "Composer is managed Airflow to orchestrate tasks with DAGs."},
	"filestore instances": {"filestore", "Filestore › Instancias", "Filestore › Instances", "la instancia de Filestore", "the Filestore instance", "las instancias", "the instances",
		"Filestore es un servidor NFS gestionado para compartir archivos entre VMs.", "Filestore is a managed NFS server to share files between VMs."},
	"source repos": {"repos", "CI/CD › Source Repositories", "CI/CD › Source Repositories", "el repositorio de código", "the source repository", "los repositorios", "the repositories",
		"Repositorios Git privados dentro del proyecto.", "Private Git repositories inside the project."},
	"config": {"", "Cloud Shell", "Cloud Shell", "la configuración de gcloud", "the gcloud configuration", "la configuración", "the configuration",
		"gcloud recuerda proyecto, región y zona por defecto para no repetirlos en cada comando.", "gcloud remembers the default project, region and zone so you do not repeat them."},
	"auth": {"", "Cloud Shell", "Cloud Shell", "la identidad activa", "the active identity", "las cuentas", "the accounts",
		"Con qué cuenta actúas determina qué puedes hacer.", "Which account you act as determines what you can do."},
	"organizations": {"iam", "IAM y administración", "IAM & Admin", "la organización", "the organization", "las organizaciones", "the organizations",
		"La jerarquía es organización → carpetas → proyectos; los permisos se heredan hacia abajo.", "The hierarchy is organization → folders → projects; permissions inherit downwards."},
	"resource-manager folders": {"iam", "IAM y administración", "IAM & Admin", "la carpeta", "the folder", "las carpetas", "the folders",
		"Las carpetas agrupan proyectos (por ejemplo, prod y dev) y heredan permisos y políticas.", "Folders group projects (e.g. prod and dev) and inherit permissions and policies."},
	"policy-intelligence": {"iam", "IAM y administración › Solucionador de problemas", "IAM & Admin › Troubleshooter", "el análisis de permisos", "the permission analysis", "los análisis", "the analyses",
		"El solucionador explica por qué alguien tiene o no un permiso.", "The troubleshooter explains why someone has or lacks a permission."},
	"network-management": {"topology", "Network Intelligence Center", "Network Intelligence Center", "la prueba de conectividad", "the connectivity test", "las pruebas", "the tests",
		"Simula el camino de un paquete y dice dónde se bloquea.", "Simulates a packet's path and says where it is blocked."},
}
